_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
load_all_enabled_fonts: 1
enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Press Start 2P&subset=cyrillic-ext#regular'
  - 'https://www.google.com/webfonts/family?family=Comic Neue&subset=latin#700'
load_on_themes: {  }
