_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 260d569c-73be-4b41-afef-2879beb7927a
name: 'Drupal Training'
mail: rajdip.roy@innoraft.com
slogan: 'The best place to understand Drupal concepts'
page:
  403: /node/4
  404: /node/3
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: rajdiproy755@gmail.com
